GO_EASY_ON_ME = 1
SDKVERSION = 7.0
ARCHS = armv7 arm64

TWEAK_NAME = actHackiOS8
actHackiOS8_FILES = Tweak.xm
actHackiOS8_FRAMEWORKS = UIKit
actHackiOS8_INSTALL_PATH = /Library/Application Support/PanoMod

include ../theos/makefiles/common.mk

include $(THEOS_MAKE_PATH)/tweak.mk
