GO_EASY_ON_ME = 1
SDKVERSION = 7.0
ARCHS = armv7

TWEAK_NAME = actHackiOS6
actHackiOS6_FILES = Tweak.xm
actHackiOS6_FRAMEWORKS = UIKit
actHackiOS6_INSTALL_PATH = /Library/Application Support/PanoMod

include ../theos/makefiles/common.mk

include $(THEOS_MAKE_PATH)/tweak.mk
