GO_EASY_ON_ME = 1
SDKVERSION = 7.0
ARCHS = armv7 arm64

TWEAK_NAME = actHackiOS7
actHackiOS7_FILES = Tweak.xm
actHackiOS7_FRAMEWORKS = UIKit
actHackiOS7_INSTALL_PATH = /Library/Application Support/PanoMod

include ../theos/makefiles/common.mk

include $(THEOS_MAKE_PATH)/tweak.mk
