GO_EASY_ON_ME = 1
SDKVERSION = 8.0
ARCHS = armv7 arm64

TWEAK_NAME = actHackiOS9
actHackiOS9_FILES = Tweak.xm
actHackiOS9_FRAMEWORKS = UIKit
actHackiOS9_INSTALL_PATH = /Library/Application Support/PanoMod

include ../theos/makefiles/common.mk

include $(THEOS_MAKE_PATH)/tweak.mk
