GO_EASY_ON_ME = 1
ARCHS = armv7 arm64

TOOL_NAME = RootHelper

RootHelper_FILES = RootHelper.m
RootHelper_OBJCFLAGS = -I$(THEOS_PROJECT_DIR) -F$(THEOS_PROJECT_DIR)

include ../theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tool.mk
